/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import bean.Account;
import bean.Transaction;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HK
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);

        RMIServer server = new RMIServer();
        server.init();

        Query query = new Query();
        ArrayList<Transaction> transactionList = query.getTransactionHistory();

        DefaultTableModel model = (DefaultTableModel) TransactionTableView.getModel();

        for (int i = 0; i < transactionList.size(); i++) {
            Object[] row = {transactionList.get(i).getCard_no1(), transactionList.get(i).getCard_no2(), transactionList.get(i).getMoney_no(), transactionList.get(i).getType(), transactionList.get(i).getCode(), transactionList.get(i).getTran_date()};
            model.addRow(row);
        }

        MainView.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {

                if (MainView.getSelectedIndex() == 0) {
                    model.getDataVector().removeAllElements();
                    ArrayList<Transaction> transactionList = query.getTransactionHistory();
                    for (int i = 0; i < transactionList.size(); i++) {
                        Object[] row = {transactionList.get(i).getCard_no1(), transactionList.get(i).getCard_no2(), transactionList.get(i).getMoney_no(), transactionList.get(i).getType(), transactionList.get(i).getCode(), transactionList.get(i).getTran_date()};
                        model.addRow(row);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        MainView = new javax.swing.JTabbedPane();
        TransactionTabView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TransactionTableView = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        fullNameTextView = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addressTextView = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneTextView = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pinTextView = new javax.swing.JPasswordField();
        createAccountButtonView = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        changeCardNoTextView = new javax.swing.JTextField();
        changePinTextView = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        changePinButtonView = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        topUpAccountTextView = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        topUpAmountTextView = new javax.swing.JTextField();
        topUpButtonView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainView.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MainViewComponentShown(evt);
            }
        });

        TransactionTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tài khoản giao dịch", "Tài khoản nhận", "Loại giao dịch", "Số tiền", "Lý do giao dịch", "Thời gian thực hiện"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TransactionTableView);

        javax.swing.GroupLayout TransactionTabViewLayout = new javax.swing.GroupLayout(TransactionTabView);
        TransactionTabView.setLayout(TransactionTabViewLayout);
        TransactionTabViewLayout.setHorizontalGroup(
            TransactionTabViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        TransactionTabViewLayout.setVerticalGroup(
            TransactionTabViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        MainView.addTab("Danh sách giao dịch", TransactionTabView);

        jLabel1.setText("Họ và tên");

        jLabel2.setText("Địa chỉ");

        jLabel3.setText("Điện thoại");

        jLabel4.setText("Mã PIN");

        createAccountButtonView.setText("Tạo tài khoản");
        createAccountButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createAccountButtonView, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fullNameTextView)
                        .addComponent(addressTextView)
                        .addComponent(phoneTextView)
                        .addComponent(pinTextView, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addressTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pinTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createAccountButtonView)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        MainView.addTab("Tạo tài khoản", jPanel8);

        jLabel5.setText("Số tài khoản");

        jLabel6.setText("Mã Pin");

        changePinButtonView.setText("Đổi mã PIN");
        changePinButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePinButtonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(46, 46, 46)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changePinButtonView, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(changePinTextView)
                        .addComponent(changeCardNoTextView, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(changeCardNoTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePinTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(changePinButtonView)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        MainView.addTab("Đổi mã PIN", jPanel10);

        jLabel7.setText("Số tài khoản");

        jLabel8.setText("Số tiền");

        topUpButtonView.setText("Nạp tiền vào tài khoản");
        topUpButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topUpButtonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topUpButtonView, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(topUpAccountTextView)
                        .addComponent(topUpAmountTextView, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(topUpAccountTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(topUpAmountTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(topUpButtonView)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        MainView.addTab("Nạp tiền", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainView)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainView, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePinButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePinButtonViewActionPerformed
        // TODO add your handling code here:
        String cardNo = changeCardNoTextView.getText();
        String pin = changePinButtonView.getText();
        Query query = new Query();
        if (cardNo.length() == 0 || pin.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                String foundCardNo = query.getAccountInfo(cardNo).getCard_no();
                query.changePin(cardNo, pin);
                JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tài khoản không tồn tại");
            }
        }
    }//GEN-LAST:event_changePinButtonViewActionPerformed

    private void createAccountButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonViewActionPerformed
        // TODO add your handling code here:
        String fullName = fullNameTextView.getText();
        String address = addressTextView.getText();
        String phone = phoneTextView.getText();
        String pin = pinTextView.getText();
        Query query = new Query();
        if (fullName.length() == 0 || address.length() == 0 || phone.length() == 0 || pin.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            query.createAccount(fullName, address, phone, pin);
            JOptionPane.showMessageDialog(null, "Tạo tài khoản thành công");
        }
    }//GEN-LAST:event_createAccountButtonViewActionPerformed

    private void topUpButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topUpButtonViewActionPerformed
        // TODO add your handling code here:
        String topUpAccount = topUpAccountTextView.getText();
        String topUpAmountString = topUpAmountTextView.getText();
        int topUpAmount = Integer.parseInt(topUpAmountString);
        System.out.println(topUpAmount);
        Query query = new Query();
        if (topUpAccount.length() == 0 || topUpAmountString.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                Account accountInfo = query.getAccountInfo(topUpAccount);
                int currentBalance = Integer.parseInt(accountInfo.getBalance().toString());
                int newBalance = currentBalance + topUpAmount;
                query.updateAccountBalance(topUpAccount, newBalance);
                query.insertTopUpTransactionHistory(accountInfo.getCard_no(), topUpAmount);
                JOptionPane.showMessageDialog(null, "Nạp tiền vào tài khoản thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tài khoản không tồn tại");
            }
        }
    }//GEN-LAST:event_topUpButtonViewActionPerformed

    private void MainViewComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MainViewComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_MainViewComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainView;
    private javax.swing.JPanel TransactionTabView;
    private javax.swing.JTable TransactionTableView;
    private javax.swing.JTextField addressTextView;
    private javax.swing.JTextField changeCardNoTextView;
    private javax.swing.JButton changePinButtonView;
    private javax.swing.JPasswordField changePinTextView;
    private javax.swing.JButton createAccountButtonView;
    private javax.swing.JTextField fullNameTextView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phoneTextView;
    private javax.swing.JPasswordField pinTextView;
    private javax.swing.JTextField topUpAccountTextView;
    private javax.swing.JTextField topUpAmountTextView;
    private javax.swing.JButton topUpButtonView;
    // End of variables declaration//GEN-END:variables
}
